# Generated by Django 5.0.7 on 2024-07-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0003_alter_inmueble_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
