# Generated by Django 5.0.7 on 2024-07-29 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0004_alter_usuario_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direccion",
            name="numero_departamento",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrendador_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
