# Generated by Django 5.0.7 on 2024-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0005_alter_direccion_numero_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="tipo_inmueble",
            field=models.CharField(
                choices=[
                    ("Casa", "Casa"),
                    ("Departamento", "Departamento"),
                    ("Parcela", "Parcela"),
                ],
                max_length=15,
            ),
        ),
    ]
