# Generated by Django 5.0.7 on 2024-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0006_alter_inmueble_tipo_inmueble"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
    ]
