# Generated by Django 5.0.7 on 2024-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0007_inmueble_disponible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudarriendo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                    ("terminada", "Terminada"),
                ],
                max_length=20,
            ),
        ),
    ]
